### ISSUE TITLE
Why programe run in one GPU.

### ISSUE THREAD

**Issue by DaobinZhu** [wenet-e2e/wenet#1709]
When I change the training set to dev, the model only runs on the 0th GPU. What could be wrong with that? The print log shows that four GPUs were detected. The screenshot as follows:

the number of model params: 46,197,266
2023-02-27 08:55:39,141 INFO Epoch 0 TRAIN info lr 8e-08
2023-02-27 08:55:39,142 INFO Epoch 0 TRAIN info lr 8e-08
2023-02-27 08:55:39,143 INFO using accumulate grad, new batch size is 4 times larger than before
2023-02-27 08:55:39,143 INFO using accumulate grad, new batch size is 4 times larger than before
2023-02-27 08:55:39,146 INFO Checkpoint: save to checkpoint exp/save_maximum_value_0.05_0.5_0.5_4gpu/init.pt
2023-02-27 08:55:39,190 INFO Epoch 0 TRAIN info lr 8e-08
2023-02-27 08:55:39,191 INFO using accumulate grad, new batch size is 4 times larger than before
2023-02-27 08:55:40,835 INFO Epoch 0 TRAIN info lr 8e-08
2023-02-27 08:55:40,837 INFO using accumulate grad, new batch size is 4 times larger than before
[W reducer.cpp:1258] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[W reducer.cpp:1258] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[W reducer.cpp:1258] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[W reducer.cpp:1258] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
2023-02-27 08:56:36,237 DEBUG TRAIN Batch 0/0 loss 175.585007 loss_att 59.813217 loss_ctc 445.719177 lr 0.00000008 rank 3
2023-02-27 08:56:36,252 DEBUG TRAIN Batch 0/0 loss 189.633469 loss_att 70.584236 loss_ctc 467.414978 lr 0.00000008 rank 2
2023-02-27 08:56:36,253 DEBUG TRAIN Batch 0/0 loss 178.094986 loss_att 66.667824 loss_ctc 438.091675 lr 0.00000008 rank 1
2023-02-27 08:56:36,314 DEBUG TRAIN Batch 0/0 loss 170.867096 loss_att 63.982761 loss_ctc 420.263885 lr 0.00000008 rank 0
Traceback (most recent call last):
  File "wenet/bin/train.py", line 309, in <module>
    main()
  File "wenet/bin/train.py", line 281, in main
    executor.train(model, optimizer, scheduler, train_data_loader, device,
  File "/home/SuXiangDong/GPU20StuA/zdb/wenet-runtime/wenet/wenet/utils/executor.py", line 78, in train
    loss_dict = model(feats, feats_lengths, target,
  File "/home/SuXiangDong/GPU20StuA/anaconda3/envs/zdb_k2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
Traceback (most recent call last):
  File "wenet/bin/train.py", line 309, in <module>
    main()
  File "wenet/bin/train.py", line 281, in main
    executor.train(model, optimizer, scheduler, train_data_loader, device,
  File "/home/SuXiangDong/GPU20StuA/zdb/wenet-runtime/wenet/wenet/utils/executor.py", line 78, in train
    loss_dict = model(feats, feats_lengths, target,
  File "/home/SuXiangDong/GPU20StuA/anaconda3/envs/zdb_k2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/SuXiangDong/GPU20StuA/anaconda3/envs/zdb_k2/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1008, in forward
    return forward_call(*input, **kwargs)
  File "/home/SuXiangDong/GPU20StuA/anaconda3/envs/zdb_k2/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1008, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/home/SuXiangDong/GPU20StuA/anaconda3/envs/zdb_k2/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 971, in _run_ddp_forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/home/SuXiangDong/GPU20StuA/anaconda3/envs/zdb_k2/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 971, in _run_ddp_forward
    return module_to_run(*inputs, **kwargs)
  File "/home/SuXiangDong/GPU20StuA/anaconda3/envs/zdb_k2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return module_to_run(*inputs, **kwargs)
  File "/home/SuXiangDong/GPU20StuA/anaconda3/envs/zdb_k2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/SuXiangDong/GPU20StuA/zdb/wenet-runtime/wenet/wenet/transformer/asr_model.py", line 98, in forward
    return forward_call(*input, **kwargs)
  File "/home/SuXiangDong/GPU20StuA/zdb/wenet-runtime/wenet/wenet/transformer/asr_model.py", line 103, in forward
    encoder_out, encoder_mask = self.encoder(speech, speech_lengths)
  File "/home/SuXiangDong/GPU20StuA/anaconda3/envs/zdb_k2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    loss_att, acc_att = self._calc_att_loss(encoder_out, encoder_mask,
  File "/home/SuXiangDong/GPU20StuA/zdb/wenet-runtime/wenet/wenet/transformer/asr_model.py", line 140, in _calc_att_loss
    return forward_call(*input, **kwargs)
  File "/home/SuXiangDong/GPU20StuA/zdb/wenet-runtime/wenet/wenet/transformer/encoder.py", line 173, in forward
    decoder_out, r_decoder_out, _ = self.decoder(encoder_out, encoder_mask,
  File "/home/SuXiangDong/GPU20StuA/anaconda3/envs/zdb_k2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/SuXiangDong/GPU20StuA/zdb/wenet-runtime/wenet/wenet/transformer/decoder.py", line 135, in forward
    xs, chunk_masks, _, _ = layer(xs, chunk_masks, pos_emb, mask_pad)
  File "/home/SuXiangDong/GPU20StuA/anaconda3/envs/zdb_k2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/SuXiangDong/GPU20StuA/zdb/wenet-runtime/wenet/wenet/transformer/encoder_layer.py", line 234, in forward
    x, tgt_mask, memory, memory_mask = layer(x, tgt_mask, memory,
  File "/home/SuXiangDong/GPU20StuA/anaconda3/envs/zdb_k2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/SuXiangDong/GPU20StuA/zdb/wenet-runtime/wenet/wenet/transformer/decoder_layer.py", line 137, in forward
    x_att, new_att_cache = self.self_attn(
  File "/home/SuXiangDong/GPU20StuA/anaconda3/envs/zdb_k2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/SuXiangDong/GPU20StuA/zdb/wenet-runtime/wenet/wenet/transformer/attention.py", line 309, in forward
    self.src_attn(x, memory, memory, memory_mask)[0])
  File "/home/SuXiangDong/GPU20StuA/anaconda3/envs/zdb_k2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/SuXiangDong/GPU20StuA/zdb/wenet-runtime/wenet/wenet/transformer/attention.py", line 183, in forward
    scores = (matrix_ac + matrix_bd) / math.sqrt(
    new_cache = torch.cat((k, v), dim=-1)
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 15.90 GiB total capacity; 2.51 GiB already allocated; 24.38 MiB free; 2.56 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 15.90 GiB total capacity; 2.61 GiB already allocated; 6.38 MiB free; 2.63 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Traceback (most recent call last):
  File "wenet/bin/train.py", line 309, in <module>
    main()
  File "wenet/bin/train.py", line 281, in main
    executor.train(model, optimizer, scheduler, train_data_loader, device,
  File "/home/SuXiangDong/GPU20StuA/zdb/wenet-runtime/wenet/wenet/utils/executor.py", line 78, in train
    loss_dict = model(feats, feats_lengths, target,
  File "/home/SuXiangDong/GPU20StuA/anaconda3/envs/zdb_k2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/SuXiangDong/GPU20StuA/anaconda3/envs/zdb_k2/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1008, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/home/SuXiangDong/GPU20StuA/anaconda3/envs/zdb_k2/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 971, in _run_ddp_forward
    return module_to_run(*inputs, **kwargs)
  File "/home/SuXiangDong/GPU20StuA/anaconda3/envs/zdb_k2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/SuXiangDong/GPU20StuA/zdb/wenet-runtime/wenet/wenet/transformer/asr_model.py", line 110, in forward
    loss_ctc = self.ctc(encoder_out, encoder_out_lens, text,
  File "/home/SuXiangDong/GPU20StuA/anaconda3/envs/zdb_k2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/SuXiangDong/GPU20StuA/zdb/wenet-runtime/wenet/wenet/transformer/ctc.py", line 60, in forward
    ys_hat = ys_hat.log_softmax(2)
RuntimeError: CUDA out of memory. Tried to allocate 38.00 MiB (GPU 0; 15.90 GiB total capacity; 2.93 GiB already allocated; 10.38 MiB free; 3.05 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
[W CUDAGuardImpl.h:111] Warning: CUDA warning: driver shutting down (function destroyEvent)
[W CUDAGuardImpl.h:112] Warning: CUDA warning: driver shutting down (function destroyEvent)
[W CUDAGuardImpl.h:113] Warning: CUDA warning: driver shutting down (function destroyEvent)
[W CUDAGuardImpl.h:114] Warning: CUDA warning: driver shutting down (function destroyEvent)
terminate called after throwing an instance of 'c10::CUDAError'
  what():  CUDA error: driver shutting down
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Exception raised from getDevice at ../c10/cuda/impl/CUDAGuardImpl.h:39 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x2b059d689612 in /home/SuXiangDong/GPU20StuA/anaconda3/envs/zdb_k2/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0xea8b52 (0x2b056e085b52 in /home/SuXiangDong/GPU20StuA/anaconda3/envs/zdb_k2/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #2: <unknown function> + 0x339668 (0x2b055370a668 in /home/SuXiangDong/GPU20StuA/anaconda3/envs/zdb_k2/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #3: c10::TensorImpl::release_resources() + 0x175 (0x2b059d66e295 in /home/SuXiangDong/GPU20StuA/anaconda3/envs/zdb_k2/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #4: <unknown function> + 0x11d700d (0x2b055593f00d in /home/SuXiangDong/GPU20StuA/anaconda3/envs/zdb_k2/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #5: <unknown function> + 0x3f6dfd4 (0x2b05586d5fd4 in /home/SuXiangDong/GPU20StuA/anaconda3/envs/zdb_k2/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #6: c10d::ProcessGroupGloo::runLoop(int) + 0x17f (0x2b05586dce8f in /home/SuXiangDong/GPU20StuA/anaconda3/envs/zdb_k2/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #7: <unknown function> + 0xc819d (0x2b055310e19d in /home/SuXiangDong/GPU20StuA/anaconda3/lib/./libstdc++.so.6)
frame #8: <unknown function> + 0x8163 (0x2b054513a163 in /lib64/libpthread.so.0)
frame #9: clone + 0x6d (0x2b0545d47f6d in /lib64/libc.so.6)

run.sh: line 159: 128792 Aborted                 python wenet/bin/train.py --gpu $gpu_id --config $train_config --data_type $data_type --symbol_table $dict --train_data data/$train_set/data.list --cv_data data/dev/data.list ${checkpoint:+--checkpoint $checkpoint} --model_dir $dir --ddp.init_method $init_method --ddp.world_size $world_size --ddp.rank $rank --ddp.dist_backend $dist_backend --num_workers 1 $cmvn_opts --pin_memory
Traceback (most recent call last):
  File "wenet/bin/train.py", line 309, in <module>
    main()
  File "wenet/bin/train.py", line 281, in main
    executor.train(model, optimizer, scheduler, train_data_loader, device,
  File "/home/SuXiangDong/GPU20StuA/zdb/wenet-runtime/wenet/wenet/utils/executor.py", line 84, in train
    loss.backward()
  File "/home/SuXiangDong/GPU20StuA/anaconda3/envs/zdb_k2/lib/python3.8/site-packages/torch/_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/SuXiangDong/GPU20StuA/anaconda3/envs/zdb_k2/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: [../third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [12.12.12.20]:174

**Comment by DaobinZhu** [comment]
It doesn't seem to be a problem with the code, so does the repulled code.

**Comment by xingchensong** [comment]
换成NCCL试试呢

**Comment by DaobinZhu** [comment]
> 换成NCCL试试呢

---------------------------
换成NCCL还是只在第0张卡跑，我debug了一下，发现在run.sh和train.py里rank都是对的，但是分配GPU的时候就全部分配到了第0张卡，很奇怪
---------------------------
data's path is /data02/imucs_data/machine84/Speech/zhudaobin/datasets/Aishell
arg1 is: /data02/imucs_data/machine84/Speech/zhudaobin/datasets/Aishell/data_aishell/wav
arg2 is: /data02/imucs_data/machine84/Speech/zhudaobin/datasets/Aishell/data_aishell/transcript
run.sh: init method is file:///home/SuXiangDong/GPU20StuA/zdb/wenet/examples/aishell/s0/exp/add_0.01_4gpu/ddp_init
total gpus is: 4
rank= 0 
rank= 1 
rank= 2 
rank= 3 
2023-02-27 15:25:41,621 INFO training on multiple gpus, this gpu 3
2023-02-27 15:25:41,628 INFO training on multiple gpus, this gpu 2
2023-02-27 15:25:41,631 INFO training on multiple gpus, this gpu 0
2023-02-27 15:25:41,639 INFO training on multiple gpus, this gpu 1
2023-02-27 15:25:41,652 INFO Added key: store_based_barrier_key:1 to store for rank: 3
2023-02-27 15:25:41,682 INFO Added key: store_based_barrier_key:1 to store for rank: 2
2023-02-27 15:26:11,704 INFO Added key: store_based_barrier_key:1 to store for rank: 1
2023-02-27 15:26:41,705 INFO Added key: store_based_barrier_key:1 to store for rank: 0
2023-02-27 15:27:11,696 INFO Rank 3: Completed store-based barrier for key:store_based_barrier_key:1 with 4 nodes.
the number of model params: 49349138
2023-02-27 15:27:41,700 INFO Rank 2: Completed store-based barrier for key:store_based_barrier_key:1 with 4 nodes.
2023-02-27 15:27:41,722 INFO Rank 1: Completed store-based barrier for key:store_based_barrier_key:1 with 4 nodes.
2023-02-27 15:27:41,761 INFO Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 4 nodes.
the number of model params: 49349138
the number of model params: 49349138
the number of model params: 49349138
gpu20:141778:141778 [0] NCCL INFO Bootstrap : Using eno1:12.12.12.20<0>
gpu20:141778:141778 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
gpu20:141778:141778 [0] NCCL INFO NET/IB : Using [0]i40iw0:1/RoCE [1]i40iw1:1/RoCE ; OOB eno1:12.12.12.20<0>
gpu20:141778:141778 [0] NCCL INFO Using network IB
NCCL version 2.10.3+cuda10.2
gpu20:141779:141779 [0] NCCL INFO Bootstrap : Using eno1:12.12.12.20<0>
gpu20:141781:141781 [0] NCCL INFO Bootstrap : Using eno1:12.12.12.20<0>
gpu20:141780:141780 [0] NCCL INFO Bootstrap : Using eno1:12.12.12.20<0>
gpu20:141779:141779 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
gpu20:141781:141781 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
gpu20:141780:141780 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
gpu20:141779:141779 [0] NCCL INFO NET/IB : Using [0]i40iw0:1/RoCE [1]i40iw1:1/RoCE ; OOB eno1:12.12.12.20<0>
gpu20:141779:141779 [0] NCCL INFO Using network IB
gpu20:141781:141781 [0] NCCL INFO NET/IB : Using [0]i40iw0:1/RoCE [1]i40iw1:1/RoCE ; OOB eno1:12.12.12.20<0>
gpu20:141781:141781 [0] NCCL INFO Using network IB
gpu20:141780:141780 [0] NCCL INFO NET/IB : Using [0]i40iw0:1/RoCE [1]i40iw1:1/RoCE ; OOB eno1:12.12.12.20<0>
gpu20:141780:141780 [0] NCCL INFO Using network IB




gpu20:141779:146539 [0] init.cc:521 NCCL WARN Duplicate GPU detected : rank 1 and rank 0 both on CUDA device 3b000
gpu20:141781:146540 [0] init.cc:521 NCCL WARN Duplicate GPU detected : rank 3 and rank 0 both on CUDA device 3b000
gpu20:141778:146532 [0] init.cc:521 NCCL WARN Duplicate GPU detected : rank 0 and rank 1 both on CUDA device 3b000
gpu20:141781:146540 [0] NCCL INFO init.cc:904 -> 5
gpu20:141780:146541 [0] init.cc:521 NCCL WARN Duplicate GPU detected : rank 2 and rank 0 both on CUDA device 3b000
gpu20:141778:146532 [0] NCCL INFO init.cc:904 -> 5
gpu20:141779:146539 [0] NCCL INFO init.cc:904 -> 5
gpu20:141780:146541 [0] NCCL INFO init.cc:904 -> 5
gpu20:141781:146540 [0] NCCL INFO group.cc:72 -> 5 [Async thread]
gpu20:141778:146532 [0] NCCL INFO group.cc:72 -> 5 [Async thread]
gpu20:141779:146539 [0] NCCL INFO group.cc:72 -> 5 [Async thread]
gpu20:141780:146541 [0] NCCL INFO group.cc:72 -> 5 [Async thread]
Traceback (most recent call last):
  File "wenet/bin/train.py", line 297, in <module>
Traceback (most recent call last):
  File "wenet/bin/train.py", line 297, in <module>
Traceback (most recent call last):
Traceback (most recent call last):
  File "wenet/bin/train.py", line 297, in <module>
  File "wenet/bin/train.py", line 297, in <module>
    main()
  File "wenet/bin/train.py", line 230, in main
    main()
  File "wenet/bin/train.py", line 230, in main
    main()
  File "wenet/bin/train.py", line 230, in main
    main()
  File "wenet/bin/train.py", line 230, in main
    model = torch.nn.parallel.DistributedDataParallel(
  File "/home/SuXiangDong/GPU20StuA/anaconda3/envs/zdb_k2/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 646, in __init__
    model = torch.nn.parallel.DistributedDataParallel(
  File "/home/SuXiangDong/GPU20StuA/anaconda3/envs/zdb_k2/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 646, in __init__
    model = torch.nn.parallel.DistributedDataParallel(
  File "/home/SuXiangDong/GPU20StuA/anaconda3/envs/zdb_k2/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 646, in __init__
    model = torch.nn.parallel.DistributedDataParallel(
  File "/home/SuXiangDong/GPU20StuA/anaconda3/envs/zdb_k2/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 646, in __init__
    _verify_param_shape_across_processes(self.process_group, parameters)
  File "/home/SuXiangDong/GPU20StuA/anaconda3/envs/zdb_k2/lib/python3.8/site-packages/torch/distributed/utils.py", line 89, in _verify_param_shape_across_processes
    _verify_param_shape_across_processes(self.process_group, parameters)
  File "/home/SuXiangDong/GPU20StuA/anaconda3/envs/zdb_k2/lib/python3.8/site-packages/torch/distributed/utils.py", line 89, in _verify_param_shape_across_processes
    _verify_param_shape_across_processes(self.process_group, parameters)
  File "/home/SuXiangDong/GPU20StuA/anaconda3/envs/zdb_k2/lib/python3.8/site-packages/torch/distributed/utils.py", line 89, in _verify_param_shape_across_processes
    _verify_param_shape_across_processes(self.process_group, parameters)
  File "/home/SuXiangDong/GPU20StuA/anaconda3/envs/zdb_k2/lib/python3.8/site-packages/torch/distributed/utils.py", line 89, in _verify_param_shape_across_processes
    return dist._verify_params_across_processes(process_group, tensors, logger)
    return dist._verify_params_across_processes(process_group, tensors, logger)
    return dist._verify_params_across_processes(process_group, tensors, logger)
RuntimeError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1191, invalid usage, NCCL version 2.10.3
ncclInvalidUsage: This usually reflects invalid usage of NCCL library (such as too many async ops, too many collectives at once, mixing streams in a group, etc).
RuntimeError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1191, invalid usage, NCCL version 2.10.3
ncclInvalidUsage: This usually reflects invalid usage of NCCL library (such as too many async ops, too many collectives at once, mixing streams in a group, etc).RuntimeError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1191, invalid usage, NCCL version 2.10.3
ncclInvalidUsage: This usually reflects invalid usage of NCCL library (such as too many async ops, too many collectives at once, mixing streams in a group, etc).    return dist._verify_params_across_processes(process_group, tensors, logger)


RuntimeError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1191, invalid usage, NCCL version 2.10.3
ncclInvalidUsage: This usually reflects invalid usage of NCCL library (such as too many async ops, too many collectives at once, mixing streams in a group, etc).

**Comment by DaobinZhu** [comment]
Every 1.0s: nvidia-smi                                               Mon Feb 27 15:58:16 2023

Mon Feb 27 15:58:16 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.118.02   Driver Version: 440.118.02   CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  On   | 00000000:3B:00.0 Off |                    0 |
| N/A   34C    P0    32W / 250W |   3476MiB / 16280MiB |      4%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla P100-PCIE...  On   | 00000000:86:00.0 Off |                    0 |
| N/A   33C    P0    27W / 250W |     10MiB / 16280MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla P100-PCIE...  On   | 00000000:AF:00.0 Off |                    0 |
| N/A   34C    P0    26W / 250W |     10MiB / 16280MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla P100-PCIE...  On   | 00000000:D8:00.0 Off |                    0 |
| N/A   34C    P0    27W / 250W |     10MiB / 16280MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0    181693      C   python                                       943MiB |
|    0    181694      C   python                                       639MiB |
|    0    181695      C   python                                       943MiB |
|    0    181697      C   python                                       943MiB |
+-----------------------------------------------------------------------------+

**Comment by DaobinZhu** [comment]
我把export CUDA_VISIBLE_DEVICES="0,1,2,3,4"故意多写了一个，但是程序居然还在跑：

----------------------------------------
Prepare data, prepare required format
run.sh: init method is file:///home/SuXiangDong/GPU20StuA/zdb/wenet-new/wenet/examples/aishell/s0/exp/conformer/ddp_init
total gpus is: 5
Failed to import k2 and icefall.         Notice that they are necessary for hlg_onebest and hlg_rescore
Failed to import k2 and icefall.         Notice that they are necessary for hlg_onebest and hlg_rescore
Failed to import k2 and icefall.         Notice that they are necessary for hlg_onebest and hlg_rescore
Failed to import k2 and icefall.         Notice that they are necessary for hlg_onebest and hlg_rescore
Failed to import k2 and icefall.         Notice that they are necessary for hlg_onebest and hlg_rescore
2023-02-28 10:51:47,104 INFO training on multiple gpus, this gpu 3
2023-02-28 10:51:47,105 INFO training on multiple gpus, this gpu 4
2023-02-28 10:51:47,106 INFO training on multiple gpus, this gpu 0
2023-02-28 10:51:47,107 INFO training on multiple gpus, this gpu 2
2023-02-28 10:51:47,114 INFO training on multiple gpus, this gpu 1
2023-02-28 10:55:17,392 INFO Added key: store_based_barrier_key:1 to store for rank: 0
2023-02-28 10:55:47,507 INFO Waiting in store based barrier to initialize process group for rank: 0, key: store_based_barrier_key:1 (world_size=5, worker_count=1, timeout=0:30:00)
2023-02-28 10:56:17,511 INFO Added key: store_based_barrier_key:1 to store for rank: 1
2023-02-28 10:56:17,541 INFO Added key: store_based_barrier_key:1 to store for rank: 4
2023-02-28 10:56:47,563 INFO Waiting in store based barrier to initialize process group for rank: 0, key: store_based_barrier_key:1 (world_size=5, worker_count=3, timeout=0:30:00)
2023-02-28 10:57:17,656 INFO Waiting in store based barrier to initialize process group for rank: 0, key: store_based_barrier_key:1 (world_size=5, worker_count=3, timeout=0:30:00)
2023-02-28 10:57:47,663 INFO Waiting in store based barrier to initialize process group for rank: 1, key: store_based_barrier_key:1 (world_size=5, worker_count=3, timeout=0:30:00)
2023-02-28 10:58:47,669 INFO Waiting in store based barrier to initialize process group for rank: 4, key: store_based_barrier_key:1 (world_size=5, worker_count=3, timeout=0:30:00)
2023-02-28 10:58:47,694 INFO Waiting in store based barrier to initialize process group for rank: 0, key: store_based_barrier_key:1 (world_size=5, worker_count=3, timeout=0:30:00)
2023-02-28 10:58:47,712 INFO Waiting in store based barrier to initialize process group for rank: 1, key: store_based_barrier_key:1 (world_size=5, worker_count=3, timeout=0:30:00)
2023-02-28 10:59:17,705 INFO Added key: store_based_barrier_key:1 to store for rank: 2
2023-02-28 10:59:47,698 INFO Added key: store_based_barrier_key:1 to store for rank: 3
2023-02-28 10:59:47,729 INFO Waiting in store based barrier to initialize process group for rank: 4, key: store_based_barrier_key:1 (world_size=5, worker_count=5, timeout=0:30:00)
2023-02-28 10:59:47,729 INFO Rank 4: Completed store-based barrier for key:store_based_barrier_key:1 with 5 nodes.
2023-02-28 11:00:17,724 INFO Waiting in store based barrier to initialize process group for rank: 0, key: store_based_barrier_key:1 (world_size=5, worker_count=5, timeout=0:30:00)
2023-02-28 11:00:17,724 INFO Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 5 nodes.
2023-02-28 11:00:47,750 INFO Waiting in store based barrier to initialize process group for rank: 1, key: store_based_barrier_key:1 (world_size=5, worker_count=5, timeout=0:30:00)
2023-02-28 11:00:47,750 INFO Rank 1: Completed store-based barrier for key:store_based_barrier_key:1 with 5 nodes.
2023-02-28 11:01:17,748 INFO Rank 2: Completed store-based barrier for key:store_based_barrier_key:1 with 5 nodes.
2023-02-28 11:01:47,755 INFO Rank 3: Completed store-based barrier for key:store_based_barrier_key:1 with 5 nodes.

----------------------------------------

这正常吗？

**Comment by DaobinZhu** [comment]
我删除了之前的conda环境，重新建了一个，解决了进程全部被分配在一个GPU的问题，但是现在又出现了老问题。

**Comment by DaobinZhu** [comment]
我似乎找到了原因，跟我之前的conda环境有关系，与代码和机器无关，我删掉了原来的环境重新创建后问题解决了。

**Comment by egorsmkv** [comment]
I had the same issue. Problem was that I had two pytorch versions on the system, one from Conda and another is from system path 

Just removed the system's one by `pip uninstall torch`

**Comment by DaobinZhu** [comment]
thank you. It seems error in different conda env.



---Original---
From: "Yehor ***@***.***&gt;
Date: Thu, Mar 2, 2023 02:27 AM
To: ***@***.***&gt;;
Cc: "Daobin ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [wenet-e2e/wenet] Why programe run in one GPU. (Issue #1709)




 
I had the same issue. Problem was that I had two pytorch versions on the system, one from Conda and another is from system path
 
Just removed the system's one by pip uninstall torch

**Comment by TeaPoly** [comment]
I had the same issue. Using `torch.cuda.set_device(args.gpu)` has solved my problem.
