### ISSUE TITLE
RuntimeError: CUDA error: CUBLAS_STATUS_INTERNAL_ERROR

### ISSUE THREAD

**Issue by srdfjy** [wenet-e2e/wenet#1740]
Hi

When I upgraded from 2.0.1 to 2.2.0 (other things have not changed), the following error occurred, what is the possible reason?

---

THCudaCheck FAIL file=../aten/src/THC/THCCachingHostAllocator.cpp line=280 error=700 : an illegal memory access was encountered
    main()
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/wenet/wenet/utils/executor.py", line 84, in train

RuntimeError: CUDA error: CUBLAS_STATUS_INTERNAL_ERROR when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
    Variable._execution_engine.run_backward(
    executor.train(model, optimizer, scheduler, train_data_loader, device,
  File "wenet/bin/train.py", line 309, in <module>
  File "/usr/local/lib/python3.8/dist-packages/torch/_tensor.py", line 307, in backward
    loss.backward()
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/__init__.py", line 154, in backward
File "wenet/bin/train.py", line 281, in main

**Comment by xingchensong** [comment]
Hi, Did you set `spec_trim = True`?

**Comment by srdfjy** [comment]
> Hi, Did you set `spec_trim = True`?

Yes, I set spec_trim=true.

**Comment by xingchensong** [comment]
I also encounter this issue when using `spec_trim=True` (not sure why ...), u can try disabling it.

**Comment by srdfjy** [comment]
I disabled spec_trim, and after training for a while, the following error still occurred. I am training u2++_conformer, using the multi-machine multi-card method.

The training data was generated with 2.0.1, could this be related?

![image](https://user-images.githubusercontent.com/66103286/224619950-3a59734f-3a58-4827-8d09-5c6faba8404c.png)

**Comment by xingchensong** [comment]
2.0.1 works perfectly even if spec_trim=True?

**Comment by srdfjy** [comment]
> 

Hi

I feel that this error seems to have nothing to do with whether to use spec_trim, because spec_trim has not been implemented in 2.0.1.

**Comment by srdfjy** [comment]
> I also encounter this issue when using `spec_trim=True` (not sure why ...), u can try disabling it.

Would you still encounter this error after disabling spec_trim?

**Comment by xingchensong** [comment]
> > I also encounter this issue when using `spec_trim=True` (not sure why ...), u can try disabling it.
> 
> Would you still encounter this error after disabling spec_trim?

No

**Comment by srdfjy** [comment]
I have solved the problem. There are two versions of CUDA drivers in the cluster. You just need to choose the higher version when installing PyTorch.
