### ISSUE TITLE
PR #1602 will result in a RuntimeError: CUDA error: CUBLAS_STATUS_INTERNAL_ERROR

### ISSUE THREAD

**Issue by srdfjy** [wenet-e2e/wenet#1803]
Recently, when upgrading from v2.1.0 to 2.2.0, the following error was thrown during training. After investigating each pull request (pr) one by one, it was found that merging #1602 would cause the above error.

1，Training without any issues was observed when checking out the branch from "fix(bin): Disable spec_trim in cv (#1599)".
2，The above error was triggered during training when checking out the branch from "[fix] fix conv2d subsampling4 mask bug (#1602)".

err
---
2023/03/31 18:36:00 2023-03-31 18:36:00,715 DEBUG TRAIN Batch 0/19100 loss 41.925217 loss_att 41.959560 loss_ctc 41.845081 lr 0.00051355 rank 4
2023/03/31 18:36:00 2023-03-31 18:36:00,730 DEBUG TRAIN Batch 0/19100 loss 27.112762 loss_att 25.464773 loss_ctc 30.958075 lr 0.00051355 rank 6
2023/03/31 18:36:09 Traceback (most recent call last):
2023/03/31 18:36:09     main()
2023/03/31 18:36:09   File "wenet/bin/train.py", line 281, in main
2023/03/31 18:36:09     loss.backward()
2023/03/31 18:36:09   File "/wenet/wenet/utils/executor.py", line 84, in train
2023/03/31 18:36:09     torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
2023/03/31 18:36:09   File "/wenet/venv102/lib/python3.8/site-packages/torch/autograd/__init__.py", line 154, in backward
2023/03/31 18:36:09 RuntimeError: CUDA error: CUBLAS_STATUS_INTERNAL_ERROR when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
2023/03/31 18:36:09   File "wenet/bin/train.py", line 309, in <module>
2023/03/31 18:36:09     Variable._execution_engine.run_backward(
2023/03/31 18:36:09     executor.train(model, optimizer, scheduler, train_data_loader, device,
2023/03/31 18:36:09   File "/wenet/venv102/lib/python3.8/site-packages/torch/_tensor.py", line 307, in backward

**Comment by robin1001** [comment]
what if you try the latest code?

**Comment by srdfjy** [comment]
The latest code also has this problem.And this problem has a small randomness that will not trigger, but if I do not merge this pr, it will definitely not trigger.

**Comment by 1215thebqtic** [comment]
I'm having the same problem. After trimming some frames, subsmapled input length is shorter than target length, and this may lead to inf ctc loss. Setting max_output_input_ratio to 0.24/0.25 after trim tail related codes may resolve this problem.

**Comment by srdfjy** [comment]
Thank you, I solved it by adjusting the min_length. Setting min_length to 0 before #1602 did not cause this problem.
