### ISSUE TITLE
Squeezeformer training breakdown with CUDA oom

### ISSUE THREAD

**Issue by bourne979** [wenet-e2e/wenet#1894]
**Describe the bug**
When training a model with my own dataset (>10k hours), I run out of memory on my GPU. I'm using 8 tesla A100 GPUs (40gb memory each). 
Configurations used: 
librispeech/s0/conf/train_squeezeformer_bidecoder_large.yaml 
librispeech/s0/conf/train_u2++_squeezeformer.yaml

**Expected behavior**
Model should have trained as expected because the configs work for librispeech. 

**Screenshots**
Traceback (most recent call last):
  File "wenet/bin/train.py", line 314, in <module>
    main()
  File "wenet/bin/train.py", line 286, in main
    executor.train(model, optimizer, scheduler, train_data_loader, device,
  File "/path/experiments/wenet/wenet/utils/executor.py", line 78, in train
    loss_dict = model(feats, feats_lengths, target,
  File "/espnet/tools/anaconda/envs/wenet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/espnet/tools/anaconda/envs/wenet/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 888, in forward
    output = self.module(*inputs, **kwargs)
  File "/espnet/tools/anaconda/envs/wenet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/path/experiments/wenet/wenet/transformer/asr_model.py", line 106, in forward
    encoder_out, encoder_mask = self.encoder(speech, speech_lengths)
  File "/espnet/tools/anaconda/envs/wenet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/path/experiments/wenet/wenet/squeezeformer/encoder.py", line 249, in forward
    xs, chunk_masks, _, _ = layer(xs, chunk_masks, pos_emb, mask_pad)
  File "/espnet/tools/anaconda/envs/wenet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/path/experiments/wenet/wenet/squeezeformer/encoder_layer.py", line 83, in forward
    x_att, new_att_cache = self.self_attn(x, x, x, mask, pos_emb, att_cache)
  File "/espnet/tools/anaconda/envs/wenet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/path/experiments/wenet/wenet/squeezeformer/attention.py", line 219, in forward
    scores = (matrix_ac + matrix_bd) / math.sqrt(
RuntimeError: CUDA out of memory. Tried to allocate 334.00 MiB (GPU 0; 39.59 GiB total capacity; 36.81 GiB already allocated; 323.19 MiB free; 37.50 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Traceback (most recent call last):
  File "wenet/bin/train.py", line 314, in <module>
    main()
**Additional context**
I tried reducing the batch sizes 8, 4 and 2, but still the training fails. Any ideas to resolve the issue? TIA!

**Comment by egorsmkv** [comment]
Check the duration of files in your dataset. Probably some files have long duration, keep them under 25 seconds or less.

**Comment by bourne979** [comment]
I can confirm that I do not have audio files > 25 seconds in the training. Still the issue persists.

**Comment by bourne979** [comment]
Okay, thanks for the information. But the same dataset works fine with u2++ conformer configuration. And with librispeech/s0/conf/train_squeezeformer_bidecoder_large.yaml configuration, I think the data processor filters out the files which are  longer than 20 seconds.

**Comment by bourne979** [comment]
I've tried with 172 million (squeezeformer_bidecoder_large) and 50 million (U2++_squeezeformer), both the configs run out of GPU memory while training.

**Comment by bourne979** [comment]
Update: Issue resolved by using batch_type set to dynamic.
