### ISSUE TITLE
NCCL issue with 3090 gpu

### ISSUE THREAD

**Issue by yuekaizhang** [wenet-e2e/wenet#372]
I have installed wenet according to readme. `conda install pytorch torchvision torchaudio=0.8.0 cudatoolkit=11.1 -c pytorch -c conda-forge` Torch version is 1.8.0.
However, I encountered the following NCCL error. I have to switch to gloo.
![image](https://user-images.githubusercontent.com/28823245/117775775-69bb6400-b26d-11eb-87e9-372387747c87.png)
Could you give some advice using nccl with 3090gpu? I have tired to degrade torch to 1.6. However, it can't work with 3090.

**Comment by yuekaizhang** [comment]
https://github.com/PyTorchLightning/pytorch-lightning/issues/4420#issuecomment-844164046
FYI, above fixed my issue.
